esphome:
  name: drv8830_test
  includes:
    - components/drv8830/drv8830.h
    - components/drv8830/drv8830.cpp


esp32:
  board: esp32-c6-devkitc-1
  framework:
    type: esp-idf

# OpenThread configuration
network:
  enable_ipv6: true

openthread:
  device_type: FTD
  tlv: !secret thread_tlv
  force_dataset: true

# Expose ESPHome API so Home Assistant or Thread border router can communicate
api:

# Logging for debugging
logger:

# OTA updates for firmware
ota:
  platform: esphome

i2c:
  id: bus_a
  sda: GPIO2
  scl: GPIO1
  scan: true
  frequency: 50000

# ===== Globals =====
globals:
  - id: drv8830_instance
    type: void*
    restore_value: false
    initial_value: 'nullptr'

# Example test switches
switch:
  - platform: template
    name: "Motor Forward 1s"
    turn_on_action:
      - lambda: |-
          auto *drv = static_cast<esphome::drv8830::DRV8830*>(id(drv8830_instance));
          if (drv == nullptr) {
            drv = new esphome::drv8830::DRV8830(id(bus_a), 0x60);
            App.register_component(drv);
            id(drv8830_instance) = static_cast<void*>(drv);
            ESP_LOGI("drv8830", "DRV8830 component created and registered");
          }
          drv->set_motor(32, drv->FORWARD);
      - delay: 1s
      - lambda: |-
          auto *drv = static_cast<esphome::drv8830::DRV8830*>(id(drv8830_instance));
          if (drv != nullptr) {
            drv->set_motor(0, drv->RELEASE);
          }

  - platform: template
    name: "Motor Backward 1s"
    turn_on_action:
      - lambda: |-
          auto *drv = static_cast<esphome::drv8830::DRV8830*>(id(drv8830_instance));
          if (drv == nullptr) {
            drv = new esphome::drv8830::DRV8830(id(bus_a), 0x60);
            App.register_component(drv);
            id(drv8830_instance) = static_cast<void*>(drv);
            ESP_LOGI("drv8830", "DRV8830 component created and registered");
          }
          drv->set_motor(32, drv->BACKWARD);
      - delay: 1s
      - lambda: |-
          auto *drv = static_cast<esphome::drv8830::DRV8830*>(id(drv8830_instance));
          if (drv != nullptr) {
            drv->set_motor(0, drv->RELEASE);
          }
